apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: central-prometheus
  namespace: central-monitoring-system
spec:
  alerting:
    alertmanagers:
      - apiVersion: v2
        name: rancher-monitoring-alertmanager
        namespace: cattle-monitoring-system
        pathPrefix: /
        port: web
  enableAdminAPI: false
  image: rancher/mirrored-prometheus-prometheus:v2.38.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  nodeSelector:
    kubernetes.io/os: linux
  paused: false
  podMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: central-monitoring
  probeNamespaceSelector: {}
  probeSelector:
    matchLabels:
      release: central-monitoring
  replicas: 1
  resources:
    limits:
      cpu: 3500m
      memory: 5000Mi
    requests:
      cpu: 2500m
      memory: 2500Mi
  retention: 10d
  routePrefix: /
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      release: central-monitoring
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      release: central-monitoring
  shards: 1
  tolerations:
    - effect: NoSchedule
      key: cattle.io/os
      operator: Equal
      value: linux
  version: v2.38.0
  enableRemoteWriteReceiver: true
  enableFeatures:
    - remote-write-receiver
---
apiVersion: v1
data:
  username: Zm9v
  password: YmFy
  auth: Zm9vOiRhcHIxJExXNlpJSHV5JEpZNGlHcGQvQWQvZ1ovQzN3WlIxcTEK
kind: Secret
metadata:
  name: prometheus-basic-auth
  namespace: central-monitoring-system
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-prometheus
  namespace: central-monitoring-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
spec:
  rules:
  - host: prometheus.central-monitoring.plgrnd.be
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-operated
            port:
              number: 9090
  tls:
  - secretName: prometheus-ingress-tls
    hosts:
      - prometheus.central-monitoring.plgrnd.be
